Revert.ion: fix build with ION_EXYNOS_STAT_LOG disabled drivers/staging/android/ion/ion.c: In function 'ion_debug_client_show': drivers/staging/android/ion/ion.c:988:11: error: 'struct ion_buffer' has no member named 'thread_comm'; did you mean 'task_comm'?      buffer->thread_comm, buffer->tid, buffer->size,            ^~ drivers/staging/android/ion/ion.c:988:32: error: 'struct ion_buffer' has no member named 'tid'; did you mean 'pid'?      buffer->thread_comm, buffer->tid, buffer->size,
Signed-off-by: arter97 <qkrwngud825@gmail.com>
Signed-off-by: UpInTheAir <upintheair.skyhigh@gmail.com> (reverted from commit 1d07ea83fcef7899292ae58662469f926d04aac6)